# Describes the format for available timer services

start:
  name: Start
  description: Start a timer
  target:
  fields:
    duration:
      description: Duration the timer requires to finish. [optional]
      default: 0
      example: "00:01:00 or 60"
      selector:
        text:

pause:
  name: Pause
  description: Pause a timer.
  target:

cancel:
  name: Cancel
  description: Cancel a timer.
  target:

finish:
  name: Finish
  description: Finish a timer.
  target:
